# Generated by Django 6.0.2 on 2026-02-22 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Note', max_length=255)),
                ('content', models.TextField(blank=True, help_text='Write your note here...')),
                ('font_color', models.CharField(default='#000000', help_text='Font color in HEX, e.g. #000000 for black', max_length=7)),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Background color in HEX, e.g. #FFFFFF for white', max_length=7)),
                ('is_pinned', models.BooleanField(default=False)),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
